on:
  - push
name: pixie-test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - run: |
          export PATH=$PATH:$GOBIN
          make test
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@master
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - run: |
          export PATH=$PATH:$GOBIN
          make lint
